using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Rhino.Mocks;
using RhinoMockExamples.Model;
using RhinoMockExamples.Service;
using NHibernate;
using RhinoMockExamples.Exceptions.BusinessRules;
using System.Transactions;
using RhinoMockExamples.Exceptions;

namespace RhinoMockExamples {

    /// <summary>
    /// Defines the Data Import Operation Type for feedback messages generated by the data import services.
    /// </summary>
    public enum DataImportFeedbackOperation {

        /// <summary>
        /// The data import operation does nothing.
        /// </summary>
        None,

        /// <summary>
        /// Data Import Operation. Insert.
        /// </summary>
        Insert,

        /// <summary>
        /// Data Import Operation. Update.
        /// </summary>
        Update
    }

    [TestClass]
    public class MockingISerializable {
        public DataImportFeedbackOperation DataImportFeedbackOperation { get; private set; }

        [TestMethod]
        public void AssertWasCalledWithoutParamsExample() {
            var constraint = MockRepository.GenerateMock<ConstraintViolationException>();
            var dataImportJobSchemaService = MockRepository.GenerateMock<IDataImportJobSchemaService>();
            var errorFeedback = new BusinessRuleErrorFeedback<Transaction>(constraint, dataImportJobSchemaService);
            Assert.IsNotNull(errorFeedback);
            dataImportJobSchemaService.AssertWasNotCalled(r => r.Test());
            constraint.ConstraintReturns = new ConstraintReturn[1];
            constraint.ConstraintReturns[0] = new ConstraintReturn();
            var errorFeedback1 = new BusinessRuleErrorFeedback<Transaction>(constraint, dataImportJobSchemaService);
            dataImportJobSchemaService.AssertWasCalled(r => r.Test());
        }

        [TestMethod]
        public void AssertWasCalledWithParamsExample() {
            var constraint = MockRepository.GenerateMock<ConstraintViolationException>();
            var dataImportJobSchemaService = MockRepository.GenerateMock<IDataImportJobSchemaService>();
            var errorFeedback = new BusinessRuleErrorFeedback<Transaction>(constraint, dataImportJobSchemaService);
            Assert.IsNotNull(errorFeedback);
            Meal meal = new Meal() { Id = 1, ServerName = "Pepe" };
            dataImportJobSchemaService.AssertWasNotCalled(r => r.Test2(Arg<Meal>.Matches(p => p.Id == 1 && p.ServerName == "Pepe")));
            constraint.ConstraintReturns = new ConstraintReturn[1];
            constraint.ConstraintReturns[0] = new ConstraintReturn();
            var errorFeedback1 = new BusinessRuleErrorFeedback<Transaction>(constraint, dataImportJobSchemaService);
            dataImportJobSchemaService.AssertWasCalled(r => r.Test2(Arg<Meal>.Matches(p => p.Id == 1 && p.ServerName == "Pepe")));
        }
    }
}
